# Generated by Django 4.2.7 on 2026-04-21 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.PositiveIntegerField()),
                ('accuracy', models.PositiveIntegerField()),
                ('errors', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Race duration in seconds')),
                ('mode', models.CharField(choices=[('30', '30 seconds'), ('60', '60 seconds'), ('inf', 'Infinite'), ('multi', 'Multiplayer')], default='30', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='typeracer_app.textpassage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(choices=[('🦊', 'Fox'), ('🐯', 'Tiger'), ('🦁', 'Lion'), ('🐺', 'Wolf'), ('🦅', 'Eagle'), ('🐉', 'Dragon'), ('🦄', 'Unicorn'), ('🐧', 'Penguin'), ('🦋', 'Butterfly'), ('🐬', 'Dolphin')], default='🦊', max_length=10)),
                ('total_races', models.PositiveIntegerField(default=0)),
                ('best_wpm', models.PositiveIntegerField(default=0)),
                ('avg_wpm', models.PositiveIntegerField(default=0)),
                ('is_guest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_race', 'First Race'), ('speed_50', 'Speed Demon (50+ WPM)'), ('speed_80', 'Type Master (80+ WPM)'), ('speed_100', 'Century Typist (100+ WPM)'), ('accuracy_100', 'Perfect Accuracy'), ('races_10', '10 Races Completed'), ('races_50', '50 Races Completed')], max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
