# Generated by Django 6.0.3 on 2026-04-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="textsnippet",
            name="content",
            field=models.TextField(default=None),
        ),
    ]
